implementacion de getprofessorByAreaId
andresmerida/academic-management pull request #44
Opened 2024-04-06 09:30 UTC by JessRod2000

Implementacion de getProfessorByAreaId usando el repositorio jdbc, además cree el endpoint para el edit en el professorController

2024-04-06 17:55 UTC, andresmerida requested changes

2024-04-06 17:55 UTC, andresmerida commented on am-core-web-service/src/main/java/org/am/core/web/rest/professor/ProfessorController.java
> +import org.springframework.web.bind.annotation.*;
no es una buena practica poner el "*"

hay que configurar tu IDE para que no lo pongo *

<img width="1025" alt="image" src="https://github.com/andresmerida/academic-management/assets/6967921/37864225-4743-4e7b-8bf1-844f8beec39a">

2024-04-06 23:18 UTC, JessRod2000 commented on am-core-web-service/src/main/java/org/am/core/web/rest/professor/ProfessorController.java
> +import org.springframework.web.bind.annotation.*;
Gracias, ya lo modifiqué y además cambié el SELECT * del JdbcRepository para solo seleccionar datos necesarios para el dto

2024-04-08 20:57 UTC, andresmerida approved these changes

2024-04-09 00:19 UTC, merged